[build]
  command = "npm run build"
  publish = ".next"

[functions]
  # Use nft (Node File Trace) bundler instead of esbuild for better native binary support
  node_bundler = "nft"
  # These files are needed for Prisma to work in serverless functions
  included_files = [
    "node_modules/.prisma/client/**",
    "node_modules/@prisma/client/**",
    "prisma/schema.prisma"
  ]
  # Prevent bundling of Prisma's native binaries
  external_node_modules = ["@prisma/client", ".prisma/client"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Ensure Prisma generates with correct binaries
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "false"
  # Enable detailed logging for debugging
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
